spring:
  application:
    name: streaming
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/streaming
    username: postgres
    password: postAmit
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true